# .streamlit/secrets.toml
OPENAI_API_KEY="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"
GOOGLE_PLACES_API_KEY="AIzaSyBbyGsZEf--TGNjWjr0xYgFSTQi7YBuYus"
