OPENAI_API_KEY= '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'
GOOGLE_PLACES_API_KEY='AIzaSyBbyGsZEf--TGNjWjr0xYgFSTQi7YBuYus'
