OPENAI_API_KEY= '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'
GOOGLE_PLACES_API_KEY='AIzaSyBbyGsZEf--TGNjWjr0xYgFSTQi7YBuYus'
